# version format
version: 1.0.{build}

# Do not build on tags
skip_tags: true

build_script:
  - cd Build
  - Package.build.cmd %APPVEYOR_BUILD_VERSION%

artifacts:
  - path: Releases\*.nupkg
  
deploy:
  - provider: NuGet
    api_key:
      secure: SPZoI6dtnTnukMvoB6U7XA6QGBR6fpseGdPE3QG0I2p2Iauz/b5Oj2hzQQp7Y2q1
    skip_symbols: false
    artifact: /.*\.nupkg/
    on:
      branch: master
